version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ayurveda
      POSTGRES_USER: ayurveda
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayurveda"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge 